// <auto-generated>
//     Généré par OtherExtension.t4 à partir des méthodes d'extension marquées [Async].
//     Ne pas modifier ce fichier manuellement.
// </auto-generated>

#nullable enable
namespace BasicComponents.Monad
{
    // Source : Monad/DataOrErrorExtension.cs
    public static class DataOrErrorAsyncExtensionOtherExtension
    {
        public static async Task<DataOrError<TResult>> SelectAsync<T, TResult>(this Task<DataOrError<T>> value, Func<T, Task<TResult>> func)
            => await (await value).SelectAsync<T, TResult>(func);

        public static async Task<DataOrError<TResult>> ThenAsync<T, TResult>(this Task<DataOrError<T>> value, Func<T, Task<DataOrError<TResult>>> func)
            => await (await value).ThenAsync<T, TResult>(func);

        public static async Task<DataOrError<T>> OrAsync<T>(this Task<DataOrError<T>> self, Func<Task<DataOrError<T>>> other)
            => await (await self).OrAsync<T>(other);

        public static async Task<T> OrElseAsync<T>(this Task<DataOrError<T>> self, Func<Task<T>> other)
            => await (await self).OrElseAsync<T>(other);
    }

    // Source : Monad/DataOrErrorStepExtension.cs
    public static class DataOrErrorStepAsyncExtensionOtherExtension
    {
        public static async Task<DataOrError<T>.Step<TResult>> OnErrorAsync<T, TError, TResult>(this Task<DataOrError<T>> self, Func<TError, Task<TResult>> func) where TError : BaseFailure
            => await (await self).OnErrorAsync<T, TError, TResult>(func);

        public static async Task<DataOrError<T>.Step<TResult>> OnErrorAsync<T, TError, TResult>(this Task<DataOrError<T>.Step<TResult>> self, Func<TError, Task<TResult>> func) where TError : BaseFailure
            => await (await self).OnErrorAsync<T, TError, TResult>(func);

        public static async Task<DataOrError<T>.Step<TResult>> OnErrorAsync<T, TError, TResult>(this Task<DataOrError<T>.Step<TResult>> self, Func<TError, Maybe<TResult>, Task<TResult>> func) where TError : BaseFailure
            => await (await self).OnErrorAsync<T, TError, TResult>(func);

        public static async Task<Check> CheckAsync<T>(this Task<DataOrError<T>.Step<T>> self, Func<T, Task<Check>> check)
            => await (await self).CheckAsync<T>(check);
    }
}
