using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ClassWrapperGenerator;

[Generator]
public class LogWrapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is InterfaceDeclarationSyntax,
                (ctx, _) => ContainsAttribute((InterfaceDeclarationSyntax)ctx.Node, ctx))
            .Where(tuple => tuple.Item1)
            .Select((tuple, _) => tuple.Item2);
        
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            (ctx, t) =>  CreateWrapper(ctx, t.Left, t.Right));
    }

    private static (bool, InterfaceDeclarationSyntax) ContainsAttribute(InterfaceDeclarationSyntax i, GeneratorSyntaxContext context)
    {
        return (i.AttributeLists
            .Select(attrListSyntax => attrListSyntax)
            .SelectMany(attrListSyntax => attrListSyntax.Attributes)
            .Any(attrSyntax =>
            {
                if (context.SemanticModel.GetSymbolInfo(attrSyntax).Symbol is not IMethodSymbol attributeSymbol)
                    return false;

                return attributeSymbol.ContainingType.ToDisplayString() == "ClassWrapper.LogWrapperAttribute";
            }), i);
    }

    private void CreateWrapper(SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<InterfaceDeclarationSyntax> interfaceDeclarations)
    {
        foreach (var interfaceDeclarationSyntax in interfaceDeclarations)
        {
            // We need to get semantic model of the class to retrieve metadata.
            var semanticModel = compilation.GetSemanticModel(interfaceDeclarationSyntax.SyntaxTree);

            // Symbols allow us to get the compile-time information.
            if (semanticModel.GetDeclaredSymbol(interfaceDeclarationSyntax)
                is not INamedTypeSymbol interfaceSymbol)
                continue;

            var namespaceName = interfaceSymbol.ContainingNamespace.ToDisplayString();

            // 'Identifier' means the token of the node. Get class name from the syntax node.
            var interfaceName = interfaceDeclarationSyntax.Identifier.Text;
            var className = interfaceName.Substring(1) + "WithLog";
            var sb = new CodeBuilder();

            sb.AppendLine($$"""
                           // <auto-generated/>

                           using System;
                           using System.Collections.Generic;
                           using Microsoft.Extensions.Logging;

                           namespace {{namespaceName}};

                           public class {{className}}
                           {
                           """);

            // Go through all class members with a particular type (property) to generate method lines.
            using (sb.Scope())
            {
                sb.AppendLine($"private {interfaceName} _inner;");
                sb.AppendLine("private ILogger _logger;");
                sb.AppendLine();
                sb.AppendLine($$"""
                                public {{className}}({{interfaceName}} inner, ILogger logger)
                                {
                                    _inner = inner;
                                    _logger = logger;
                                }
                                """);
                sb.AppendLine();
                
                foreach (var member in interfaceSymbol.GetMembers())
                {
                    if (member is IPropertySymbol p)
                    {
                        sb.AppendLine(WriteProperty(p));
                        sb.AppendLine();
                    }
                    else if (member is IMethodSymbol m 
                             && m.MethodKind != MethodKind.PropertyGet
                             && m.MethodKind != MethodKind.PropertySet)
                    {
                        sb.AppendLine(WriteMethode(m));
                        sb.AppendLine();
                    }
                }
            }

            sb.AppendLine("}");
            // Add the source code to the compilation.
            context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static string WriteProperty(IPropertySymbol p)
    {
        var s = $$"""
                  {{p.Type.ToDisplayString()}} {{p.Name}} 
                  {
                      get 
                      {
                        _logger.LogInformation($"Get {_inner.GetType().Name}.{{p.Name}}");
                         return _inner.{{p.Name}};
                      }
                  """;
        if (p.SetMethod != null)
            s += $$"""
                   
                       set 
                       {
                          _logger.LogInformation($"Set {_inner.GetType().Name}.{{p.Name}}");
                          _inner.{{p.Name}} = value;
                       }
                   """;
        s += "\r\n}";
        return s;
    }
    
    private static string WriteMethode(IMethodSymbol m)
    {
        return $$"""
                  {{m.ReturnType.ToDisplayString()}} {{m.Name}}({{string.Join(", ", m.Parameters.Select(p => p.ToDisplayString()))}})
                  {
                      _logger.LogInformation($"Call {_inner.GetType().Name}.{{m.Name}}");
                      {{(!m.ReturnsVoid ? "return " : "")}}_inner.{{m.Name}}({{string.Join(", ", m.Parameters.Select(p => p.Name))}});
                  }
                  """;
    }
}