using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using ClassWrapperGenerator.Extendables;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ClassWrapperGenerator;

[Generator]
public class PartialClassGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validValuesProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => RetrieveInformation((ClassDeclarationSyntax)ctx.Node, ctx))
            .Where(tuple => tuple.match);
        var provider = validValuesProvider.Select((tuple, _)  => tuple.syntax);
        var additionalFilesPatternProvider = validValuesProvider.Select((tuple, _) => tuple.additionalFilesPattern);

        context.RegisterSourceOutput(context.CompilationProvider
                .Combine(provider.Collect())
                .Combine(additionalFilesPatternProvider.Collect())
                .Combine(context.AdditionalTextsProvider.Collect()),
            (ctx, t) =>
            {
                var compilation = t.Left.Left.Left;
                var classDeclarationSyntaxes = t.Left.Left.Right;
                var additionalFilesPattern = t.Left.Right;
                var additionalTexts = t.Right;
                CreatePartialPart(ctx, compilation, classDeclarationSyntaxes, FilterAdditionalFiles(additionalFilesPattern, additionalTexts).ToImmutableArray());
            });
    }

    private static IEnumerable<ImmutableArray<AdditionalText>> FilterAdditionalFiles(
        ImmutableArray<ImmutableArray<Regex>> additionalFilesPattern, 
        ImmutableArray<AdditionalText> additionalTexts)
    {
        foreach (var patterns in additionalFilesPattern)
            yield return [..additionalTexts.Where(text => patterns.Any(regex => regex.IsMatch(text.Path)))];
    }
    
    private (bool match, ClassDeclarationSyntax syntax, ImmutableArray<Regex> additionalFilesPattern) RetrieveInformation(ClassDeclarationSyntax syntax, GeneratorSyntaxContext ctx)
    {
        var attr = syntax.AttributeLists
            .Select(attrListSyntax => attrListSyntax)
            .SelectMany(attrListSyntax => attrListSyntax.Attributes)
            .Select(attrSyntax => (attrSyntax, attributeSymbol: ModelExtensions.GetSymbolInfo(ctx.SemanticModel, attrSyntax).Symbol as IMethodSymbol))
            .FirstOrDefault(tuple =>
            {
                if (tuple.attributeSymbol == null)
                    return false;

                return tuple.attributeSymbol.ContainingType.ToDisplayString() == "ClassWrapper.ExtendAttribute";
            });
        var pattern = new List<string>();

        if (attr.attributeSymbol != null)
        {
            pattern = attr.attrSyntax.ArgumentList?.Arguments
                .Select(arg => arg.Expression switch
            {
                LiteralExpressionSyntax literalExpressionSyntax => literalExpressionSyntax.ToString().Trim('"'),
                _ => throw new NotImplementedException()
            }).ToList() ?? [];
        }
        return (attr.attributeSymbol != null, syntax, pattern.Select(p => new Regex(p)).ToImmutableArray());
    }

    private void CreatePartialPart(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classDeclarationSyntaxes,
        ImmutableArray<ImmutableArray<AdditionalText>> additionalFilesPattern)
    {
        foreach (var (classSyntax, additionalFilePattern) in classDeclarationSyntaxes.Zip(additionalFilesPattern))
        {
            var semanticModel = compilation.GetSemanticModel(classSyntax.SyntaxTree);

            if (ModelExtensions.GetDeclaredSymbol(semanticModel, classSyntax) is not INamedTypeSymbol classSymbol)
                continue;
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSyntax.Identifier.Text;
            var sb = new ClassBuilder(namespaceName, className)
            {
                IsPartial = true
            };
            sb.Header.AppendLine("// <auto-generated/>");
            try
            {

                foreach (var extendable in FindGenerator(classSymbol.GetAttributes(), compilation))
                    extendable?.ExtendClass(sb, classSymbol, semanticModel, additionalFilePattern);
                foreach (var member in classSymbol.GetMembers())
                {
                    foreach (var generator in FindGenerator(member.GetAttributes(), compilation))
                    {
                        switch (member)
                        {
                            case IFieldSymbol fieldSymbol:
                                generator?.ExtendField(sb, fieldSymbol, semanticModel);
                                break;
                            case IMethodSymbol methodSymbol:
                                generator?.ExtendMethod(sb, methodSymbol, semanticModel);
                                break;
                            case IParameterSymbol parameterSymbol:
                                generator?.ExtendParameter(sb, parameterSymbol, semanticModel);
                                break;
                            case IPropertySymbol propertySymbol:
                                generator?.ExtendProperty(sb, propertySymbol, semanticModel);
                                break;
                        }
                    }
                }
            }
            catch (Exception e)
            {
                throw new Exception($"{e.Message} :: ({string.Join(" ||| ", e.StackTrace.Split(CodeBuilder.NewLine).Take(3))})",
                    e);
            }
            context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private IEnumerable<IExtendable?> FindGenerator(ImmutableArray<AttributeData> attributes, Compilation compilation)
    {
        foreach (var attribute in attributes)
        {
            if (attribute.AttributeClass!.GetAttributes().FirstOrDefault(attrData => attrData.AttributeClass.ToDisplayString() == "ClassWrapper.ExtendGeneratorAttribute")
                is {} extendAttribute)
            {
                if (extendAttribute.ConstructorArguments[0].Value is not string generatorName)
                    break;
                IExtendable? generator;
                object?[] typedConstants = [];

                try
                {
                    var generatorType = FindType(generatorName);
                    typedConstants = TypedConstantsToObject(attribute.ConstructorArguments, compilation).ToArray();

                    generator = (IExtendable?)Activator.CreateInstance(generatorType, typedConstants);
                }
                catch (Exception e)
                {
                    throw new InvalidOperationException(
                        $"Could not create extend generator {generatorName}({string.Join(", ", typedConstants.ToList())}). " +
                        $"{e.Message}");
                }
                yield return generator;
            }
        }
    }

    private IEnumerable<object?> TypedConstantsToObject(ImmutableArray<TypedConstant> constants, Compilation compilation)
    {
        return constants.Select(c =>
        {
            switch (c.Kind)
            {
                case TypedConstantKind.Primitive:
                    return c.Value;
                case TypedConstantKind.Type:
                    return compilation.GetTypeByMetadataName(c.Value!.ToString()!)
                           ?? throw new ArgumentException($"Parameter of type {c.Value!.ToString()} cannot be found.");
                case TypedConstantKind.Array:
                    return TypedConstantsToObject(c.Values, compilation).ToArray();
                default:
                    throw new ArgumentOutOfRangeException();
            }
        });
    }

    private Type FindType(string typeName)
    {
        return Assembly.GetAssembly(GetType())!.GetTypes()
            .First(type => type.Name == typeName);
    }
}